apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-ntts-2025-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-ntts-2025-model-deployment
  template:
    metadata:
      labels:
        app: hackathon-ntts-2025-model-deployment
    spec:
      containers:
        - name: hackathon-ntts-2025-app
          image: rayaberova/hackathon-ntts-2025:main
          imagePullPolicy: Always
          env:
            # env var for s3 connexion
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://minio.lab.sspcloud.fr
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mc-s3
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mc-s3
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            # env var for setting mlflow model registry server
            - name: MLFLOW_TRACKING_URI
              value: https://projet-hackathon-ntts-2025-mlflow.user.lab.sspcloud.fr
            # env var for setting models uri which will be deployed
            - name: MLFLOW_MODEL_NAME
              value: Segmentation-multiclass
            - name: MLFLOW_MODEL_VERSION
              value: "3"
            - name: MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR
              value: "false"
          resources:
            limits:
              memory: "75Gi"
              cpu: "100000m"
            requests:
              memory: "8Gi"
              cpu: "1000m"