apiVersion: v1
kind: Service
metadata:
  name: hackathon-ntts-2025-model-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: hackathon-ntts-2025-model-deployment