project:
  type: website
  render:
    - /src/**/index.qmd

    - index.qmd
    - /cards/*.qmd

website:
  page-navigation: true
  title: "Presentation French Team for Eurostat Hackathon 2025"
  site-url: "https://inseefrlab.github.io/hackathon-ntts-2025/"
  repo-url: "https://github.com/InseeFrLab/hackathon-ntts-2025.git"
  open-graph: true
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: LICENSE
  navbar:
    logo: https://upload.wikimedia.org/wikipedia/fr/thumb/1/10/Logo_Insee.svg/1200px-Logo_Insee.svg.png
    align: center
    title: false
    collapse-below: lg
    right:
      - icon: github
        href: "https://github.com/InseeFrLab/hackathon-ntts-2025.git"
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Accueil 
format:
  html:
    theme:
      light: [cosmo, style/styles.scss]
      dark: [cyborg, style/styles.scss]
    reference-location: margin
    toc: true
    code-copy: true
    code-overflow: wrap
    include-in-header: "style/fontawesome.html"
    header-includes: |
        <link rel="icon" type="image/png" sizes="32x32" href="src/_extensions/InseeFrLab/onyxia/favicon-32x32.png">