apiVersion: v1
kind: Secret
metadata:
  name: my-geoserver-creds
type: Opaque
stringData:
  username: "XXXX"  # Remplacer par le nom d'utilisateur souhaité
  pwd: "XXX"  # Remplacer par le mot de passe souhaité